<!DOCTYPE html>
<html>
<head>
    
    <title>COFFE Library</title>
</head>
   
       
<body>
    <?php
    include 'css.css';
    include 'list.php';
    ?>
    
    <center>
           <br><br>
        <div id="d1" class="d1"> 
              <h1>COFFE LIBRARY</h1></div>

              <div id="d2"class="d2"> 
                <h2>ABOUT THE LIBRARY</h2>
               <div style="  width: 45%; float: left;">
                <p>
            
                  <h1>Coffee Library for all the books you want and love, 
                    such as novels and many diverse books that every
                     male and female reader loves, 
                     at beautiful and imaginative prices.</h1>
               </p>
            </div>
            <div style="width: 45%; float: right;">
               <img style="width: 50%;height: 300px;" src="img/l44.jpg">
            </div>
    </center>
</body>
</html>