<!DOCTYPE html>
<html>
<head>
    
    <title>COFFE Library</title>
</head>
   
       
<body>
    <?php
    include 'css.css';
    include 'list.php';
    ?>
    
    <center>
          
         <div  id="d3" class="d3"> 
              <br><br>
            <h2>BEST SELLER BOOKS</h2>
            <div style="float: left; width: 25%;">
                <img src="img/books/l1.jpg" style="width:200px; height:200px;">
                      <h2>author: د.خولة الحمدي</h2>
                      <label>price: 500TL</label>
                     </div>
            <div style="float: left; width: 25%;">
                <img src="img/books/l2.jpg" style="width:200px; height:200px;">
                <h2>author: اسلام جمال</h2>
                <label>price: 400TL</label>
            </div>

            <div style="float: left; width: 25%;">
                <img src="img/books/l3.jpg" style="width:200px; height:200px;">
                <h2>author: اثير عبدالله</h2>
                <label>price: 300TL</label>
            </div>

        




        
    </center>
</body>
</html>